[workspace]
members = [
    "ch02_01",
    "ch02_02",
    "ch02_03",
    "ch02_04",
    "ch02_05",
    "ch02_06",
    "ch02_07",
    "ch03_01",
    "ch03_04",
    "ch04_03",
    "ch05_03",
    "ch06_03",
    "ch07_04",
    "ch08_03",
    "ch09_03",
    "ch10_01",
    "ch10_02",
]